### ISSUE TITLE
Changing example scenario fails with linter error

### ISSUE THREAD

**Issue by bocytko** [zalando/typhoon#132]
I'm using the docker version (latest). I started the container and was able to successfully run the example scenario via `http://localhost:8080`. Basically this tests the typhoon itself, but I could see meaningful data being displayed.

Now I have a service that I want to load test running at port `8081`. Unfortunately, changing the scenario (even just the port in the URL) fails with a linter error:

```
Failed to load resource: the server responded with a status of 400 (Bad Request)

typhoon.js:485 Uncaught (in promise) TypeError: error.map is not a function
    at Object.<anonymous> (typhoon.js:485)
    at Object.error (monad.js:27)
    at typhoon.js:796
```

I used `Chrome 57.0.2987.133`. The docker logs show:

```
19:38:55.930 [error] gen_server <0.26020.0> terminated with reason: econnrefused
19:38:55.932 [error] CRASH REPORT Process <0.26020.0> with 0 neighbours exited with reason: econnrefused in gen_server:terminate/7
19:38:55.932 [error] Supervisor knet_tcp_sup had child knet_tcp started with {knet_tcp,start_link,undefined} at <0.26020.0> exit with reason econnrefused in context child_terminated
```

Scenario:

```
-module(xgqcsv3yz9h8).
-compile({parse_transform, monad}).
%%
%% typhoon scenario file
%% see https://github.com/zalando/typhoon/blob/master/docs/scenario.md
%%

%% 
-export([title/0, t/0, n/0, ttl/0]).
-export([init/0, run/1]).

%%
%% human readable scenario title.
title() -> 
   "No title".

%% time to execute workload in milliseconds.
t() ->
   60000.

%% number of concurrent sessions to spawn in the cluster.
n() ->
   2.

%% time to live for connection spawned by scenario.
ttl() ->
   1000.

%%%----------------------------------------------------------------------------   
%%%
%%% actions
%%%
%%%----------------------------------------------------------------------------   

%%
%% init scenario configuration
init() ->
   do([m_state ||
      _ =< undefined,
      return(_)
   ]).

%%
%% execute scenario, the operation is repeated  until `t()` is expired. 
run(_Config) ->
   do([m_state ||
      _ <- request(),
      return(_)
   ]).

request() ->
   do([m_http ||
      _ /= new("http://localhost:8081/health/peer"),
      _ /= x('GET'),
      _ /= h("Connection", "keep-alive"),
      _ /= r(),
      return(_)
   ]).
```

I can `curl http://localhost:8081/health/peer` successfully. Maybe I misunderstood the docs. Can you advise on the errors I'm getting?

**Comment by fogfish** [comment]
Thank you for reporting the issue!

Here I do see a two problem
1. the visualization of measurement. This is bug, I would address it by new issue #133 and fix asap
1. the lint error. The second one, I'd like to get more feedback from you...

Could you please share the signature of your docket image? I'd like to validate linter behaviour in that version.
```
docker images | grep typhoon
``` 

The linter is designed to fail with error in following cases:
1. scenario syntax is not valid
1. scenario cannot be executed agains SUT due to mis-configuration of network addresses 

Your case is impacted by second case. 

The end-point `http://localhost:8081` is translated into localhost from container perspective. The tool tries to generate traffic to itself on port 8081 but nothing is hosted there. Thus  `econnrefused` socket error is generated. If you'd like to load-test a local service that runs on your laptop then you have either:
1. package your service into docker container, spawn it at docker and then modify script to point into right IP address (you can use links or docker compositions)
1. use binary version of the tool. They are available for Mac and Linux and run tool with your host environment as daemon process. 
```
export REL=$(curl -s https://github.com/zalando/typhoon/releases/latest | sed -n 's/.*tag\/\([^"]*\).*/\1/p')
curl -L -O https://github.com/zalando/typhoon/releases/download/${REL}/typhoon-${REL}.x86_64.Darwin.bundle
sudo bash typhoon-${REL}.x86_64.Darwin.bundle

/usr/local/typhoon/bin/typhoon foreground 
```

**Comment by fogfish** [comment]
release 1.0.2 incorporates UI improvements discussed above.

**Comment by bocytko** [comment]
Yeah, silly me not recognising that the load tester within a docker container cannot reach a service outside of it. Thanks for pointing that out and fixing #134.

Here the requested signature:

```
$ docker images | grep typhoon
registry.opensource.zalan.do/hunt/typhoon   latest              e515bdbaa872        4 weeks ago         555MB
```
