### ISSUE TITLE
Some kind of plugins

### ISSUE THREAD

**Issue by mancvso** [zalando/typhoon#53]
Hi there!
If I were to extend Typhoon to execute other protocols like ømq, AMQP or Kafka, where should I start?

**Comment by fogfish** [comment]
Hello,
 
The project uses extendable network stack that implement concept of smart sockets. The library is limited only to udp, tcp, ssl, http, ws protocols but it should be extendable to other protocols.   
https://github.com/kfsm/knet/blob/master/src/knet.erl#L67 

However, Typhoon scenario module limits its usage for http protocol only
https://github.com/zalando/typhoon/blob/master/apps/scenario/src/scenario.erl#L96
Essentially, this is an artificial limitation. It would make sense to extend scenario module to support other protocols from knet library. We need to design better approach of connection management within given scenario. I would suggest to take a look `lint` feature of the tool. It is easy to trace an approach of I/O design. I am talking about

The tool implement lint end-point. You can validate scenario syntax, compile it and execute against SUT.

```
curl -v -XPOST http://192.168.99.100:8080/lint/example \
   -H 'Content-Type: application/erlang' \
   --data-binary @examples/skeleton.erl
```

1. lint entry point
https://github.com/zalando/typhoon/blob/master/apps/zephyrus/src/zephyrus_lint.erl#L43

2. netpool allocator use by lint
https://github.com/zalando/typhoon/blob/master/apps/zephyrus/src/zephyrus_lint.erl#L84
 
3. schedule scenario execution
https://github.com/zalando/typhoon/blob/master/apps/zephyrus/src/zephyrus_lint.erl#L57

4. construction of I/O function 
https://github.com/zalando/typhoon/blob/master/apps/scenario/src/scenario.erl#L141

5. actual network I/O
https://github.com/zalando/typhoon/blob/master/apps/scenario/src/scenario.erl#L307

As you can see, current I/O monad is stateless it only know ID of I/O pool. We need to make it statefull, allowing to pass socket map between request. After that we can enable raw tcp protocol to Typhoon and open possibility to implement other protocols.

**Comment by fogfish** [comment]
Sorry of delay! Let's follow up on your concern... 

The adoption of new protocols was blocked by design of `scenario` application. I've took you suggestion seriously and re-build the protocol execution. Now, each protocol is implemented using concept similar to state monad:
https://github.com/fogfish/datum/blob/master/src/m_state.erl  
https://github.com/fogfish/datum/blob/master/doc/monad.md

As beginning I've implemented two monads for address http(s), tcp and ssl protocols:

case of http
https://github.com/zalando/typhoon/blob/master/examples/skeleton.erl
https://github.com/zalando/typhoon/blob/master/apps/njord/src/m_http.erl

case of raw socket
https://github.com/zalando/typhoon/blob/master/apps/njord/src/m_sock.erl
https://github.com/zalando/typhoon/blob/master/examples/socket.erl
  
as a summary, the "introduction" of new protocol is transparent to the tool, just and it's pure functional wrapper that is compatible with m_state monad (see m_http, m_sock for examples).

So far, I do not have any other protocols in my roadmap then protocols supported by knet library. However, I can consider other protocol(s) libraries as well if there is demand. Any thought on protocol?

Keep in-mind that this feature is exists only in master branch. I am still testing it. The binary and docker releases will be shipped in 2 weeks...

**Comment by mancvso** [comment]
Wow, thank you very much for the detailed explanation and work.
I'm still in a previous stage, but I want to test

Binary
HTTP/2, AMQP, MQTT
Textual
STOMP, HTTP/1.1

as they are the protocols for my thesis.

**Comment by fogfish** [comment]
Hello,

So far HTTP/1.1 is only supported out of box. There is a discussion to enable HTTP/2 but I do not have a clear schedule yet... No other protocols are considered yet, so contribution is welcome! 

AMQP - easies way is to integrated RMQ client library to the project using state monad wrapper.
MQTT - either integrate a client provided here https://github.com/emqtt or implement it using knet primitives
STOMP -  implement it using knet primitives or raw socket
